import:
- logstash-plugins/.ci:travis/travis.yml@1.x

before_install:
- sudo sysctl -w vm.max_map_count=262144 # due ES bootstrap requirements

jobs:
  include:
    - stage: "Integration Tests"
      env: INTEGRATION=true SNAPSHOT=true LOG_LEVEL=info ELASTIC_STACK_VERSION=8.previous
    - env: INTEGRATION=true SNAPSHOT=true LOG_LEVEL=info ELASTIC_STACK_VERSION=8.current
    - stage: "Secure Integration Tests"
      env: SECURE_INTEGRATION=true INTEGRATION=true LOG_LEVEL=info ELASTIC_STACK_VERSION=8.current SNAPSHOT=true
