import:
- logstash-plugins/.ci:travis/travis.yml@1.x

before_install:
- sudo sysctl -w vm.max_map_count=262144 # due ES bootstrap requirements

env:
- INTEGRATION=false ELASTIC_STACK_VERSION=7.x
- INTEGRATION=false ELASTIC_STACK_VERSION=7.x SNAPSHOT=true
- INTEGRATION=false ELASTIC_STACK_VERSION=8.x SNAPSHOT=true
- INTEGRATION=true ELASTIC_STACK_VERSION=7.x
- INTEGRATION=true ELASTIC_STACK_VERSION=7.x SNAPSHOT=true
- INTEGRATION=true ELASTIC_STACK_VERSION=8.x SNAPSHOT=true
- SECURE_INTEGRATION=true INTEGRATION=true ELASTIC_STACK_VERSION=7.x
- SECURE_INTEGRATION=true INTEGRATION=true ELASTIC_STACK_VERSION=7.x ES_SSL_SUPPORTED_PROTOCOLS=TLSv1.3
- SECURE_INTEGRATION=true INTEGRATION=true ELASTIC_STACK_VERSION=7.15.0
